# -*- coding: utf-8 -*-
"""Juego_mundial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CCv8le0YQwLPMc3h1FM99dMGplKbcc8S
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import requests
import random

# Crear pie de pagina con los datos de contacto de los creadores
footer = """
<style>
    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        z-index: 10;
        width: 100%;
        background-color: rgb(14, 17, 23);
        color: black;
        text-align: center;
    }
    .footer p {
        color: white;
    }
</style>
<div class="footer">
    <p>App desarrollada por: <br />
    Andres Felipe Ramirez Suarez <br />
    Contactenos: <a href="#">aramirezsu@unal.edu.co</a>
</div>
"""
st.markdown(footer,unsafe_allow_html=True)

# Título de la aplicación
st.title("Reconoce El jugador por su foto")

#Instrucciones del juego
# Lista de equipos que participaron en el Mundial 2022
equipos = [
    "Qatar", "Alemania", "Dinamarca", "Brasil", "Bélgica", "Francia",
    "Croacia", "España", "Serbia", "Inglaterra", "Suiza", "Países Bajos",
    "Argentina", "Irán", "Corea del Sur", "Japón", "Arabia Saudita", "Uruguay",
    "Ecuador", "Canadá", "Ghana", "Senegal", "Portugal", "Polonia", "Túnez",
    "Marruecos", "Camerún", "Estados Unidos", "México", "Gales",
    "Australia", "Costa Rica"
]

# Definir las fases del torneo
fases = ["Octavos de final", "Cuartos de final", "Semifinales", "Final"]

# Función para calcular resultados
def calcular_resultados():
    ganador = None
    for fase in fases:
        if len(equipos) >= 2:
            equipo1 = random.choice(equipos)
            equipos.remove(equipo1)
            equipo2 = random.choice(equipos)
            equipos.remove(equipo2)
            ganador = random.choice([equipo1, equipo2])
            equipos.append(ganador)
    return ganador

# Crear la aplicación de Streamlit
st.title("Score Goals")
st.header("Simulación del Mundial 2022")

# Botón para calcular nuevos resultados
if st.button("Calcular Resultados"):
    ganador = calcular_resultados()

    # Anunciar al ganador del Mundial
    st.subheader("Ganador del Mundial 2022")
    st.success(f"¡{ganador} es el ganador del Mundial 2022!")