# -*- coding: utf-8 -*-
"""reconocer_jugador.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CCv8le0YQwLPMc3h1FM99dMGplKbcc8S
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import requests
import random

#URL de datasets
url_players = ("https://raw.githubusercontent.com/aramirezsuarez"
              "/Score_Goals/main/datasets/players.csv")

# Cargar el DataFrame desde la URL
df_players = pd.read_csv(url_players)

# Crear pie de pagina con los datos de contacto de los creadores
footer = """
<style>
    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        z-index: 10;
        width: 100%;
        background-color: rgb(14, 17, 23);
        color: black;
        text-align: center;
    }
    .footer p {
        color: white;
    }
</style>
<div class="footer">
    <p>App desarrollada por: <br />
    Andres Felipe Ramirez Suarez <br />
    Contactenos: <a href="#">aramirezsu@unal.edu.co</a>
</div>
"""
st.markdown(footer,unsafe_allow_html=True)

# Título de la aplicación
st.title("Reconoce El jugador por su foto")

#Instrucciones del juego